#!/bin/bash

### BEGIN INIT INFO
# Provides:          round2_service
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Round2.py at boot time
# Description:       Enable service provided by Round2.py
### END INIT INFO

/usr/bin/python3 /home/sunrise/Documents/Rounds.py &

exit 0
